### ISSUE TITLE
Update to Listmonk release 2.5.1

### ISSUE THREAD

**Issue by frankievalentine** [railwayapp-templates/listmonk#2]
Update template to newest release of Listmonk (2.5.1) [here](https://github.com/knadh/listmonk/releases/tag/v2.5.1)

**Comment by brody192** [comment]
This template uses the latest version tag of Listmonk by default, and the latest version on docker hub is indeed 2.5.1

**Comment by candidexmedia** [comment]
For reference: here are the upgrade instructions for Railway: https://listmonk.app/docs/upgrade/#railway
