### ISSUE TITLE
Not able to deploy the app on listmonk!

### ISSUE THREAD

**Issue by kulterryan** [railwayapp-templates/listmonk#3]
Getting errors while deploying the app.

![image](https://github.com/railwayapp-templates/listmonk/assets/36154235/59155839-3234-4f47-8e78-5772e3dad8bb)

**Comment by brody192** [comment]
@kulterryan This template is a bit old, give this one a try [https://railway.app/template/-zHmwJ](https://railway.app/template/-zHmwJ)

**Comment by kulterryan** [comment]
@brody192 it appears to be deleted now :)

**Comment by brody192** [comment]
It has, as I was given ownership of the original listmonk template and have updated that one.
 I've edited my message but here's the template link too [https://railway.app/template/listmonk](https://railway.app/template/listmonk)

**Comment by brody192** [comment]
Railway's routing table tables a minute or so to update, please be patient.

**Comment by kcritesh** [comment]
@brody192 got it. sorry for trouble 🙏
